/*
 * TRANSLATION FILE (ENGLIGH)
 * 
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 * 
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "Erguer objeto";
STR_R3F_LOG_action_heliporter_fait = """%1"" acoplado.";
STR_R3F_LOG_action_heliport_larguer = "Soltar objeto";
STR_R3F_LOG_action_heliport_parachute = "Lançar objeto";
STR_R3F_LOG_action_heliport_larguer_fait = """%1"" solto.";
STR_R3F_LOG_action_heliport_attente = "Enganchando... (%1)";
STR_R3F_LOG_action_heliport_echec_attente = "Abortado! Fique pairando durante o engate.";

STR_R3F_LOG_action_deplacer_objet = "Pegar ""%1""";
STR_R3F_LOG_action_relacher_objet = "Soltar ""%1""";
STR_R3F_LOG_action_aligner_pente = "Ajuste ao declive";
STR_R3F_LOG_action_aligner_sol = "Ajustar com o chão";
STR_R3F_LOG_action_aligner_horizon = "Ajustar horizontalmente";
STR_R3F_LOG_action_tourner = "Girar esquerda/direita (X/C)";
STR_R3F_LOG_action_rapprocher = "Aproximar/afastar (F/R)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "Você não pode entrar num veículo enquanto está carregando este objeto!";
STR_LOCK_OBJECT = "Travar esse objeto";
STR_UNLOCK_OBJECT = "Destravar esse objeto";

STR_R3F_LOG_action_charger_deplace = "Carregar no veículo";
STR_R3F_LOG_action_selectionner_objet_charge = "Carregar ""%1"" no...";
STR_R3F_LOG_action_charger_selection = "...carregar no ""%1""";
STR_R3F_LOG_action_selectionner_objet_fait = "Agora, selecione o destino pro ""%1""...";
STR_R3F_LOG_action_charger_en_cours = "Carregamento em curso...";
STR_R3F_LOG_action_charger_fait = "O ""%1"" foi carregado no ""%2"".";
STR_R3F_LOG_action_charger_pas_assez_de_place = "Não há espaço suficiente para este objeto neste veículo!";

STR_R3F_LOG_action_remorquer_direct = "Rebocar ""%1""";
STR_R3F_LOG_action_remorquer_deplace = "Rebocar o objeto";
STR_R3F_LOG_action_detacher = "Desacoplar objeto";
STR_R3F_LOG_action_detacher_fait = "Objeto desacoplado.";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "Apenas o motorista pode separar esse objeto.";

STR_R3F_LOG_action_contenu_vehicule = "Ver o conteúdo do veículo";
STR_R3F_LOG_action_decharger_en_cours = "Descarga em andamento...";
STR_R3F_LOG_action_decharger_fait = "O ""%1"" foi descarregado do veículo.";
STR_R3F_LOG_action_decharger_deja_fait = "O objeto já foi descarregado!";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "Uma vez liberado, esse objeto não vai mais ser móvel manualmente.<br/>Você confirmar a ação?";

STR_R3F_LOG_action_ouvrir_usine = "Abra a fábrica de criação";
STR_R3F_LOG_action_creer_en_cours = "Criação em andamento...";
STR_R3F_LOG_action_creer_fait = "O ""%1"" foi criado.";
STR_R3F_LOG_action_creer_pas_assez_credits = "A fábrica não tem créditos suficientes para criar este objeto.";
STR_R3F_LOG_action_revendre_usine_direct = "Enviar de volta ""%1"" para a fábrica";
STR_R3F_LOG_action_revendre_usine_deplace = "Enviar de volta para a fábrica";
STR_R3F_LOG_action_revendre_usine_selection = "...enviar de volta para a fábrica";
STR_R3F_LOG_action_revendre_en_cours = "Enviando de volta para a fábrica...";
STR_R3F_LOG_action_revendre_fait = "O ""%1"" foi enviado de volta para a fábrica.";
STR_R3F_LOG_action_revendre_decharger_avant = "Você não pode enviá-lo de volta, enquanto houver conteúdo!";

STR_R3F_LOG_mutex_action_en_cours = "A operação atual não está terminada!";
STR_R3F_LOG_joueur_dans_objet = "Há um jogador no objeto ""%1""!";
STR_R3F_LOG_objet_en_cours_transport = "O ""%1"" já está em trânsito!";
STR_R3F_LOG_objet_remorque_en_cours = "Impossível, porque o ""%1"" está rebocando outro objeto!";
STR_R3F_LOG_trop_loin = "Impossível, porque o ""%1"" está muito longe!";

STR_R3F_LOG_dlg_CV_titre = "Conteúdo do veículo";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "Carregando: %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "DESCARREGAR";
STR_R3F_LOG_dlg_CV_btn_fermer = "CANCELAR";

STR_R3F_LOG_dlg_LO_titre = "Fábrica de criação";
STR_R3F_LOG_dlg_LO_credits_restants = "Créditos remanescentes: %1";
STR_R3F_LOG_dlg_LO_btn_creer = "CRIAR";
STR_R3F_LOG_dlg_LO_btn_fermer = "CANCELAR";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "Propriedades";
STR_R3F_LOG_nom_fonctionnalite_side = "Lado";
STR_R3F_LOG_nom_fonctionnalite_places = "Assentos";
STR_R3F_LOG_nom_fonctionnalite_passif = "Pode ser:";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "Deslocado pelo jogador";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "Levantado";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "Rebocado";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "Transportado";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "Custo de carregamento %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "Pode:";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "Levanta";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "Reboque";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "Transporte";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "carregamento máximo %1";

STR_R3F_LOG_deverrouillage_en_cours = "Desbloqueio... (%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "Desbloqueio cancelado! Segure a mira no objeto durante a contagem regressiva.";
STR_R3F_LOG_deverrouillage_succes_attente = "Objeto desbloqueado.";
STR_R3F_LOG_action_deverrouiller = "Desbloqueio ""%1""";
STR_R3F_LOG_action_deverrouiller_impossible = "Objeto bloqueado";